#! /bin/bash

    function CVT_txt_0_2(){
        name=${1%.*}
        pandoc -f markdown -t beamer --pdf-engine=xelatex -V colorlinks=true ${CVT_pb_std[0,2]} ${CVT_tpl_std[0,2]} $2 $3 -o $name.pdf $1
    }
